### ISSUE TITLE
error when installing sampler

### ISSUE THREAD

**Issue by SaraVarela** [BrunoVilela/sampler#1]
Hi @BrunoVilela 

I am trying to use the package and I had the following error when installing: 

"ERROR: this R is version 3.2.1, package 'sampler' requires R >= 3.4" 

is R 3.4 absolutely necessary for this package?

If not, take care in "Description" with 
"Depends:
    R (>= 3.4)" 

you might want to allow people to install the package independently of their version of R (or, set a softer rule, e.g. >=3.0).

**Comment by BrunoVilela** [comment]
Sure I will do it, thanks!
